baseURL = 'https://mahdiabbasi13811381.github.io/negarkhaneh/'
title = 'نگارخانه | نمونه کارهای عکاسی'
languageCode = 'fa-ir'
defaultContentLanguage = 'fa'

[params]
description = 'نگارخانه ای از آثار هنری و نوشته‌های ادبی'
subtitle = 'نگار برای تصاویر، فرسته برای نوشته‌ها'

[menu]
[[menu.main]]
name = 'صفحه اصلی'
url = '/'
weight = 1

[[menu.main]]
name = 'نگاره‌ها'
url = '/negar/'
weight = 2

[[menu.main]]
name = 'نوشته‌ها'
url = '/feresteh/'
weight = 3

[[menu.main]]
name = 'دربارهٔ من'
url = '/about/'
weight = 4

[[menu.main]]
name = 'تماس'
url = '/contact/'
weight = 5

# تنظیمات نمایش برای هر بخش
[outputs]
home = ['HTML', 'RSS', 'JSON']
section = ['HTML', 'RSS']
