backend:
  name: github
  repo: mahdiabbasi13811381/negarkhaneh
  branch: main
  base_url: https://mahdiabbasi13811381.github.io
  auth_endpoint: negarkhaneh/admin/index.html

# تنظیمات ضروری
site_url: https://mahdiabbasi13811381.github.io/negarkhaneh
display_url: https://mahdiabbasi13811381.github.io/negarkhaneh

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "پست‌های وبلاگ"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "عنوان", widget: "string" }
      - { name: "date", label: "تاریخ", widget: "datetime" }
      - { name: "body", label: "محتوا", widget: "markdown" }
